import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const URL="https://fanpkaufpnyengidikie.supabase.co";
const KEY="sb_publishable_ST1YckAd6kCrdm0jwzDHYw_CsuNPteI";
const db=createClient(URL,KEY);
const $=id=>document.getElementById(id);
let leads=[],current=null;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const date=v=>v?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";
function showLogin(msg=""){$("login").classList.remove("hidden");$("app").classList.add("hidden");$("error").textContent=msg}
function showApp(email){$("login").classList.add("hidden");$("app").classList.remove("hidden");$("userEmail").textContent=email||"Usuário"}
async function load(){const {data,error}=await db.from("leads").select("*").order("created_at",{ascending:false});if(error){console.error(error);alert("Erro ao carregar leads: "+error.message);return}leads=data||[];render()}
function render(){const start=new Date();start.setHours(0,0,0,0);$("total").textContent=leads.length;$("today").textContent=leads.filter(x=>new Date(x.created_at)>=start).length;$("hot").textContent=leads.filter(x=>+x.score>=70).length;$("converted").textContent=leads.filter(x=>x.status==="Convertido").length;$("recent").innerHTML=leads.slice(0,6).map(x=>`<div class="row"><div><div class="name">${esc(x.name||"Sem nome")}</div><div class="sub">${esc(x.email||"")}</div></div><span class="badge">${esc(x.status||"Novo")}</span><b>${+x.score||0}/100</b><div class="sub">${date(x.created_at)}</div></div>`).join("")||'<div class="empty">Nenhum lead ainda.</div>';renderTable()}
function renderTable(){const q=$("search").value.toLowerCase().trim(),s=$("filter").value;const a=leads.filter(x=>(!s||x.status===s)&&(!q||`${x.name||""} ${x.email||""} ${x.phone||""}`.toLowerCase().includes(q)));$("empty").classList.toggle("hidden",a.length>0);$("tbody").innerHTML=a.map(x=>`<tr><td><b>${esc(x.name||"Sem nome")}</b><br><span class="sub">${esc(x.email||"—")}</span></td><td>${esc(x.phone||"—")}</td><td>${esc(x.profile||"—")}</td><td><b>${+x.score||0}</b></td><td><span class="badge">${esc(x.status||"Novo")}</span></td><td>${date(x.created_at)}</td><td><button class="open" data-id="${x.id}">Abrir</button></td></tr>`).join("");document.querySelectorAll(".open").forEach(b=>b.onclick=()=>openLead(+b.dataset.id))}
function openLead(id){current=leads.find(x=>x.id===id);if(!current)return;$("dName").textContent=current.name||"Lead";$("dEmail").textContent=current.email||"—";$("dPhone").textContent=current.phone||"—";$("dProfile").textContent=current.profile||"—";$("dGoal").textContent=current.goal||"—";$("dLevel").textContent=current.level||"—";$("dScore").textContent=+current.score||0;$("dChallenge").textContent=current.challenge||"—";$("dMessage").textContent=current.message||"—";$("dStatus").value=current.status||"Novo";$("dScoreInput").value=+current.score||0;$("dNotes").value=current.notes||"";$("modal").classList.remove("hidden")}
async function save(){if(!current)return;const payload={status:$("dStatus").value,score:Math.max(0,Math.min(100,+$("dScoreInput").value||0)),notes:$("dNotes").value.trim(),updated_at:new Date().toISOString()};const {error}=await db.from("leads").update(payload).eq("id",current.id);if(error){alert("Não foi possível salvar: "+error.message);return}$("modal").classList.add("hidden");await load()}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("error").textContent="";const {data,error}=await db.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error){$("error").textContent="E-mail ou senha incorretos.";return}showApp(data.user.email);load()};
$("reset").onclick=async e=>{e.preventDefault();const email=$("email").value.trim();if(!email){$("error").textContent="Digite seu e-mail primeiro.";return}const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.href});$("error").textContent=error?error.message:"Se o e-mail existir, enviaremos um link de recuperação."};
$("logout").onclick=async()=>{await db.auth.signOut();showLogin()};$("refresh").onclick=load;$("search").oninput=renderTable;$("filter").onchange=renderTable;$("close").onclick=()=>$("modal").classList.add("hidden");$("save").onclick=save;
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(n=>n.classList.remove("active"));b.classList.add("active");const d=b.dataset.view==="dashboard";$("dashboard").classList.toggle("hidden",!d);$("leads").classList.toggle("hidden",d);$("title").textContent=d?"Dashboard":"Leads"});
(async()=>{const {data:{session}}=await db.auth.getSession();if(session){showApp(session.user.email);await load()}else showLogin()})();
